spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static/
  data:
    elasticsearch:
      cluster-nodes: 111.202.69.244:9300